use_frameworks!

target 'MOPhoneNumberInputViewController_Example' do
  pod 'UXPhoneNumberInput', :path => '../'

  target 'MOPhoneNumberInputViewController_Tests' do
    inherit! :search_paths


  end
end
